### Introduction

Aiyai mates! Welcome to GraphIt R Shiny application. 

There are 3 main purposes of this application:<br>
1. Users can interact with the interface to have some insights on the relationships of the variables in a breast cancer data set.<br>
2. This application can also make breast cancer predictions for users based on the user input. <br>
3. This application also shows the accuracy and consistency of the prediction result based on the actual breast cancer data set.

Resource of dataset: [Breast Cancer Wisconsin (Diagnostic) Data Set](https://www.kaggle.com/datasets/uciml/breast-cancer-wisconsin-data?datasetId=180&language=R&outputs=Visualization)

***

### How to use this application?
#### Attribute Description and Data Summary
Click this tab to see the descriptions of each feature that is provided here.<br> 
The breast cancer dataset is summarized by providing the Mininum, 1st Quartile, Median, Mean, 3rd Quartile and the Maximum values for each attribute. <br>
The "Info" provides the number of observations, number of variables(attributes) and data type for each attribute.

***

#### Exloratory Data Analysis
Data visualization on the data set (EDA tab).

- **User Input**
  + User can choose the type of graph.
  + Next, user can choose variable for x-axis & y-axis for **scatter plot**.
  + For **histogram, bar graph and box plot**, user can only choose **x-axis** variable.
  + For **histogram and box plot**, user cannot choose **diagnosis** as variable.
  + Below the custommized graph, there is a correlation plot.
  
- **Usage of the graphs/plot**  
  + Scatter plot let user to visualize the distribution of data for two variables and look into their relationships.
  + Histogram summarizes the total occurences for a value for a continuous variable.
  + Bar graph summarizes the total occurences for a value for a categorical variable.
  + Box plot let the users to visualize  the summary of a variable and find the outliers.
  + Correlation plot summarize the significance of each variable for the diagnosis.

***
#### Model Prediction
Prediction on diagnosis of breast cancer with based on *user input measurement values* (Prediction tab).

- Feature Selection
- Principle component
- PCA (40%->90%)
- Accuracy of trained model
- Train model: Logistic Regression, SVM, Naive Bayes, Random Forest

***

#### Model Training
This tab is about the process of model training and how we improve the model for the breast cancer prediction. <br> 
1. Data Preparation - including initial selected features, target variable, Principal Component Analysis(PCA), train result and test result.<br>
2. Set Up Baseline Model - Multiple ML Models are trained and the results are shown in this section. <br>
3. Fine-tune - The best model is selected to fine tune and improve through the combination of cost and gamma.


***

